import { Inter } from "next/font/google";
import StyledComponentsRegistry from "../../lib/registry";
import "./globals.css";
import { Container } from "@mui/material";
import { PharmaContextProvider } from "../../context/PharmaContext";
import NavBar from "../../components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PharmaContextProvider>
          <StyledComponentsRegistry>
            <Container maxWidth="xl">
              <NavBar />
              {children}
            </Container>
          </StyledComponentsRegistry>
        </PharmaContextProvider>
      </body>
    </html>
  );
}
